In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import sys

In [2]:
# Load the required input data
x_train = np.load('Data/x_train.npy')
x_test = np.load('Data/x_test.npy')
x_train = np.squeeze(x_train)
x_test = np.squeeze(x_test)

lab_train = np.load('Data/lab_train.npy')
lab_test = np.load('Data/lab_test.npy')
lab_train = np.squeeze(lab_train)
lab_test = np.squeeze(lab_test)

# Load weights and biases of the autoencoder trained previously
w = np.load('Data/ae-weights.npy')
b = np.load('Data/ae-biases.npy')

# Parameters
learning_rate = 0.001
training_epochs = 20

# Network Parameters
n_hidden_1 = 128
n_hidden_2 = 50
n_input = 256
n_classes = 3

# tf Graph input
x = tf.placeholder("float", [None, n_input])
y = tf.placeholder("float", [None, n_classes])

weights = {
    'h1': tf.constant(w[()]['encoder_h1']),
    'h2': tf.constant(w[()]['encoder_h2']),
    'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
}
biases = {
    'b1': tf.constant(b[()]['encoder_b1']),
    'b2': tf.constant(b[()]['encoder_b2']),
    'out': tf.Variable(tf.random_normal([n_classes]))
}

# weights = {
#     'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
#     'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
#     'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
# }
# biases = {
#     'b1': tf.Variable(tf.random_normal([n_hidden_1])),
#     'b2': tf.Variable(tf.random_normal([n_hidden_2])),
#     'out': tf.Variable(tf.random_normal([n_classes]))
# }

# Create model
def multilayer_perceptron(x, weights, biases):
    layer_1 = tf.add(tf.matmul(x, weights['h1']), biases['b1'])
    layer_1 = tf.nn.relu(layer_1)

    layer_2 = tf.add(tf.matmul(layer_1, weights['h2']), biases['b2'])
    layer_2 = tf.nn.relu(layer_2)

    out_layer = tf.matmul(layer_2, weights['out']) + biases['out']
    return out_layer

pred = multilayer_perceptron(x, weights, biases)

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred, labels=y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

init = tf.initialize_all_variables()


In [4]:

Bsize = 256
Tsize = len(x_train)
Nbatch = int(Tsize/Bsize)
if Tsize/(Bsize*1.0) != Nbatch:
    Nbatch = Nbatch + 1
print 'Total Number of Batches:',Nbatch
nEpochs = 1000

sess = tf.Session()
# with tf.Session() as sess:
sess.run(init)
for epoch in range(nEpochs):
    print "Epoch:",epoch+1,

    avg_cost = 0.
    for i in range(Nbatch):
        if(i+1 == Nbatch):
            a = (i)*Bsize+1
            b = Tsize
        else:
            a = (i)*Bsize+1
            b = (i+1)*Bsize

        # print a,b
        batch_x = x_train[a-1:b]
        batch_y = lab_train[a-1:b]
        # print np.shape(x_train),np.shape(batch_x)
        _, c = sess.run([optimizer, cost], feed_dict={x: batch_x,
                                                      y: batch_y})
        avg_cost = avg_cost + c

    print "cost:",avg_cost/(Nbatch*1.0)
print("Optimization Finished!")
correct_prediction = tf.equal(tf.argmax(pred, 1), tf.argmax(y, 1))

accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
print("Accuracy:", sess.run(accuracy, feed_dict = {x: x_test, y: lab_test}))

Total Number of Batches: 47
Epoch: 1 cost: 3883.88123512
Epoch: 2 cost: 3116.37658225
Epoch: 3 cost: 2440.31482567
Epoch: 4 cost: 1772.4387862
Epoch: 5 cost: 1139.20017916
Epoch: 6 cost: 664.34558698
Epoch: 7 cost: 363.365078784
Epoch: 8 cost: 200.784399154
Epoch: 9 cost: 173.637539397
Epoch: 10 cost: 173.379376351
Epoch: 11 cost: 168.918586082
Epoch: 12 cost: 164.126752813
Epoch: 13 cost: 159.179803808
Epoch: 14 cost: 154.175374376
Epoch: 15 cost: 149.420703563
Epoch: 16 cost: 144.805479253
Epoch: 17 cost: 140.078289681
Epoch: 18 cost: 135.635014148
Epoch: 19 cost: 131.461929727
Epoch: 20 cost: 127.518191398
Epoch: 21 cost: 124.010360718
Epoch: 22 cost: 120.708243593
Epoch: 23 cost: 117.673136123
Epoch: 24 cost: 114.869198332
Epoch: 25 cost: 112.399879699
Epoch: 26 cost: 110.035990289
Epoch: 27 cost: 107.794096358
Epoch: 28 cost: 105.759642662
Epoch: 29 cost: 103.89354162
Epoch: 30 cost: 101.963668742
Epoch: 31 cost: 100.269908986
Epoch: 32 cost: 98.6992765386
Epoch: 33 cost: 97.10135

In [5]:
correct_prediction = tf.equal(tf.argmax(pred, 1), tf.argmax(y, 1))

accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
print("Accuracy:", sess.run(accuracy, feed_dict = {x: x_test, y: lab_test}))

('Accuracy:', 0.77073735)


In [41]:
t1 = sess.run(correct_prediction,feed_dict = {x: x_test, y: lab_test})


In [35]:
s1,s2 = sess.run([t3,t4] , feed_dict = {x: x_test, y: lab_test})

In [42]:
t1

array([False, False,  True, ...,  True,  True,  True], dtype=bool)

In [46]:
t2 = tf.reduce_sum(tf.cast(t1,"float"))
print sess.run(t2)

1782.0


In [47]:
len(t1)

2604

[[ -1.67639103e+01   1.43366706e+00  -1.73662201e+02]
 [ -2.30107754e-01   1.99578514e+01  -1.27069565e+02]
 [  5.67272043e+00  -5.49980011e+01  -2.42515545e+01]
 ..., 
 [ -3.72981323e+03  -5.08399609e+03  -1.44776474e+02]
 [ -4.04178979e+03  -4.91788623e+03   8.46981873e+02]
 [ -3.63589966e+03  -5.14513574e+03  -2.30477264e+02]]


In [12]:
t1 = tf.argmax(pr,1)

In [16]:
t2 = sess.run(t1)

In [18]:
print t2

[1 1 0 ..., 2 2 2]
